Repository ipti/br.tag, pull requests merged in 2023-04, with the labels that each got.

#263 feature: quarterly report from TAG - Buzios/RJ
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  js/reports/index/functions.js
  themes/default/views/reports/buzios/headers/headBuziosI.php
  themes/default/views/reports/buzios/headers/headBuziosII.php
  themes/default/views/reports/buzios/headers/headBuziosIII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportFirstYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIV.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreI.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportSecondYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportThreeYear.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#264 fix: corrections quarterly report
  app/controllers/ReportsController.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportFirstYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIV.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreI.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportSecondYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportThreeYear.php
Labels: Melhoria

#281 Fix: Added handling for the 'create_date' field in the 'classroom' table. If the value is null, a query will be made to the 'log' table to obtain the creation date of the classroom.
  app/migrations/3.4.7_add_sagres_tables/add_sagres_tables.sql
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/ProvisionAccounts.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/_form.php
  app/modules/sagres/views/default/index.php
  js/sagres/form/validations.js
Labels: hotfix

#282 fix: final grade average
  CHANGELOG.md
  app/controllers/EnrollmentController.php
  app/controllers/ReportsController.php
  config.php
  themes/default/views/enrollment/grades.php
Labels: hotfix
