Repository ipti/br.tag, pull requests merged in 2023-07, with the labels that each got.

#361 Feature/filiation birthday (version 3.28.70)
  CHANGELOG.md
  app/messages/pt_br/default.php
  app/migrations/3.28.70_add_filiation_birthday/Script.sql
  app/models/StudentIdentification.php
  config.php
  js/student/form/validations.js
  themes/default/views/student/_form.php
Labels: Funcionalidade

#363 Feature/show password (version 3.29.71)
  CHANGELOG.md
  config.php
  js/admin/form/validations.js
  js/site/login.js
  themes/default/views/admin/_form.php
  themes/default/views/admin/editPassword.php
  themes/default/views/site/login.php
Labels: Funcionalidade

#364 Feat/classdiary module (version 3.30.71)
  CHANGELOG.md
  app/config/main.php
  app/controllers/ClassesController.php
  app/modules/classdiary/ClassdiaryModule.php
  app/modules/classdiary/controllers/DefaultController.php
  app/modules/classdiary/resources/classDiary/_initialization.js
  app/modules/classdiary/resources/classDiary/functions.js
  app/modules/classdiary/resources/index/functions.js
  app/modules/classdiary/services/ClassesService.php
  app/modules/classdiary/services/DisciplineService.php
  app/modules/classdiary/services/InstructorService.php
  app/modules/classdiary/services/StudentService.php
  app/modules/classdiary/usecases/GetClassContents.php
  app/modules/classdiary/usecases/GetClassrooms.php
  app/modules/classdiary/usecases/GetDiscipline.php
  app/modules/classdiary/usecases/GetDisciplines.php
  app/modules/classdiary/usecases/GetFrequency.php
  app/modules/classdiary/usecases/GetStudent.php
  app/modules/classdiary/usecases/SaveClassContents.php
  app/modules/classdiary/usecases/SaveFrequency.php
  app/modules/classdiary/usecases/SaveJustification.php
  app/modules/classdiary/views/default/_frequencyElementDesktop.php
  app/modules/classdiary/views/default/_frequencyElementMobile.php
  app/modules/classdiary/views/default/classDiary.php
  app/modules/classdiary/views/default/index.php
  app/modules/classdiary/views/default/studentClassDiary.php
  app/modules/sagres/views/default/index.php
  config.php
  js/classes/frequency/_initialization.js
  sass/css/main.css
  sass/scss/_badge.scss
  sass/scss/_base.scss
  sass/scss/_button.scss
  sass/scss/_cards.scss
  sass/scss/_filter-bar.scss
  sass/scss/_filter_bar.scss
  sass/scss/_functions.scss
  sass/scss/_grid.scss
  sass/scss/_helpers.scss
  sass/scss/_icons.scss
  sass/scss/_table.scss
  sass/scss/_tag.scss
  sass/scss/components/_field-multiselect.scss
  sass/scss/components/_field-tarea.scss
  sass/scss/components/_field-text.scss
  sass/scss/main.scss
  themes/default/css/template.css
  themes/default/views/classes/classContents.php
  themes/default/views/instructor/_form.php
  themes/default/views/layouts/fullmenu.php
  themes/default/views/school/_form.php
  themes/default/views/wizard/configuration/index.php
Labels: Funcionalidade

#365 Feature/turn on registration tab (version 3.31.71)
  CHANGELOG.md
  config.php
  themes/default/views/student/_form.php
Labels: Funcionalidade

#366 Feature/report teachers by stage and teachers by school (version 3.33.71)
  CHANGELOG.md
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  config.php
  themes/default/img/reportsIcon/school_teacher.svg
  themes/default/img/reportsIcon/stage_teachers.svg
  themes/default/views/reports/TeachersBySchool.php
  themes/default/views/reports/TeachersByStage.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#367 Fix/transport report query correction (version 3.33.72)
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
Labels: hotfix

#362 Fix/refactoring class contents (version 3.28.71)
  CHANGELOG.md
  config.php
  js/classes/class-contents/_initialization.js
  js/courseplan/form/_initialization.js
  sass/css/main.css
  sass/scss/_badge.scss
  sass/scss/_button.scss
  sass/scss/_grid.scss
  sass/scss/_tokens.scss
  themes/default/views/classes/classContents.php
  themes/default/views/courseplan/form.php
Labels: Melhoria

#368 Fix/selection of schools in the user form (version 3.33.73)
  CHANGELOG.md
  sass/css/main.css
  sass/scss/_grid.scss
  themes/default/views/admin/_form.php
Labels: Melhoria

#370 Refactor/removal of calculate average button (version 3.34.74)
  CHANGELOG.md
  config.php
  js/enrollment/grades/_initialization.js
  themes/default/views/enrollment/grades.php
Labels: Melhoria

#371 Fix/hide sagres button
  themes/default/views/layouts/fullmenu.php
Labels: Melhoria

#369 Feature/transfer report (version 3.34.73) - NOT MERGE
  CHANGELOG.md
  app/controllers/ReportsController.php
  themes/default/views/reports/StudentByClassroomReport.php
  themes/default/views/reports/TransferReport.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#380 Feature/statistical data (version 3.37.76)
  CHANGELOG.md
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  config.php
  instance.php
  sass/css/main.css
  sass/scss/_icons.scss
  themes/default/views/reports/StatisticalData.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#381 Feature/enrollment report PCD column (version 3.37.77)
  CHANGELOG.md
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  config.php
  js/reports/StudentsWithDisabilitiesPerClassroom/_initialization.js
  js/reports/StudentsWithDisabilitiesPerSchool/_initialization.js
  sass/css/main.css
  sass/scss/_modal.scss
  themes/default/views/reports/EnrollmentPerClassroomReport.php
  themes/default/views/reports/StudentsWithDisabilitiesPerClassroom.php
  themes/default/views/reports/StudentsWithDisabilitiesPerSchool.php
  themes/default/views/reports/StudentsWithDisabilitiesRelationReport.php
  themes/default/views/reports/index.php
Labels: Melhoria

#383 Feature/teacher training report (version 3.38.77)
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  themes/default/views/reports/buzios/TeacherTraining.php
  themes/default/views/reports/buzios/headers/headBuziosVI.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#391 Hotfix/enrollment report (version 3.40.80)
  CHANGELOG.md
  config.php
  themes/default/views/reports/EnrollmentPerClassroomReport.php
Labels: Melhoria
