Repository ipti/br.tag, pull requests merged in 2023-06, with the labels that each got.

#341 Fix/generate RA API
  CHANGELOG.md
  app/models/InstructorIdentification.php
  app/models/InstructorTeachingData.php
  app/modules/sedsp/models/DadosAluno.php
  app/modules/sedsp/usecases/AddRACodeToTAG.php
  app/modules/sedsp/usecases/IdentifyStudentRACode.php
  config.php
  instance.php
  js/datatables/init.js
Labels: hotfix

#343 Feature/cns report
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  themes/default/views/reports/CnsReport.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#349 Feat: Added new validations for sagres
  app/migrations/2023-05-06-inconsistency-sagres/query.sql
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/models/SagresModel.php
  app/modules/sagres/models/SagresValidations.php
  app/modules/sagres/views/default/inconsistencys.php
  app/modules/sagres/views/default/index.php
Labels: Melhoria

#348 Fix/changelog and print icon reports
  app/messages/pt_br/default.php
  themes/default/css/template.css
  themes/default/views/admin/changelog.php
  themes/default/views/reports/BFReport.php
  themes/default/views/reports/ClassroomWithoutInstructorRelationReport.php
  themes/default/views/reports/CnsReport.php
  themes/default/views/reports/ComplementarActivityAssistantByClassroomReport.php
  themes/default/views/reports/DisciplineAndInstructorRelationReport.php
  themes/default/views/reports/EducationalAssistantPerClassroomReport.php
  themes/default/views/reports/EnrollmentComparativeAnalysisReport.php
  themes/default/views/reports/IncompatibleStudentAgeByClassroomReport.php
  themes/default/views/reports/InstructorsPerClassroomReport.php
  themes/default/views/reports/OutOfTownStudentsReport.php
  themes/default/views/reports/SchoolProfessionalNumberByClassroomReport.php
  themes/default/views/reports/StudentByClassroomReport.php
  themes/default/views/reports/StudentInstructorNumbersRelationReport.php
  themes/default/views/reports/StudentPendingDocument.php
  themes/default/views/reports/StudentSpecialFood.php
  themes/default/views/reports/StudentsBetween5And14YearsOldReport.php
  themes/default/views/reports/StudentsByClassroomReport.php
  themes/default/views/reports/StudentsInAlphabeticalOrderRelationReport.php
  themes/default/views/reports/StudentsUsingSchoolTransportationRelationReport.php
  themes/default/views/reports/StudentsWithDisabilitiesRelationReport.php
  themes/default/views/reports/buzios/quarterly/EvaluationFollowUpReport.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilHighSchool.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilSixNineYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyFollowUpReport.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportFirstYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIV.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreI.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportSecondYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportThreeYear.php
Labels: Melhoria

#350 Hotfix/school performance by activities
  CHANGELOG.md
  app/controllers/FormsController.php
  config.php
  themes/default/css/template.css
  themes/default/views/forms/EnrollmentGradesReport.php
Labels: hotfix

#351 Feature/manager tab in school form (version 3.26.64)
  CHANGELOG.md
  app/controllers/SchoolController.php
  app/migrations/3.26.64_add_manager_identification/add_manager_identification.sql
  app/models/ManagerIdentification.php
  app/models/SchoolIdentification.php
  config.php
  js/school/form/_initialization.js
  js/school/form/functions.js
  js/school/form/pagination.js
  js/school/form/validations.js
  themes/default/views/school/_form.php
  themes/default/views/school/create.php
  themes/default/views/school/update.php
Labels: Funcionalidade

#353 Fix/student exclusion alert, report support professional and foreign student country (version 3.26.67)
  CHANGELOG.md
  app/controllers/ReportsController.php
  app/controllers/StudentController.php
  config.php
  js/student/form/validations.js
  themes/default/views/student/_form.php
  themes/default/views/student/index.php
  themes/default/views/student/update.php
Labels: hotfix

#357 Fix: modified query to get data from the manager in the new table
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix

#359 Fix: removed function that caused error when generating the sagres file
  app/modules/sagres/controllers/DefaultController.php
Labels: hotfix

#358 Feat: added registration of various classes in sedsp
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/mappers/ClassroomMapper.php
  app/modules/sedsp/models/EscolaTurmas.php
  app/modules/sedsp/views/default/index.php
Labels: Funcionalidade
