Repository ipti/br.tag, pull requests merged in 2023-09, with the labels that each got.

#428 Feature/php code patters with phpmd
  ruleset.xml
Labels: Melhoria

#449 Fix/save grade results
  Dockerfile
  app/controllers/AdminController.php
  app/controllers/EnrollmentController.php
Labels: hotfix

#448 Feat/total number of students enrolled (version 3.55.89)
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  sass/css/main.css
  sass/scss/_icons.scss
  themes/default/views/reports/TotalNumberOfStudentsEnrolled.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#424 Fix/NIS field will be mandatory when the Bolsa Família participant box is checked
  js/student/form/validations.js
Labels: Melhoria

#450 Fix/Sonar Cloud Bugs High Severity:ambulance:
  app/controllers/ReportsController.php
  app/modules/resultsmanagement/resources/common/css/resultsmanagement.css
  app/modules/resultsmanagement/resources/common/css/style.css
  app/modules/schoolreport/resources/common/css/style.css
  css/screen.css
  sass/scss/_accordeon.scss
  themes/default/css/select2.css
  themes/default/css/template.css
  themes/default/css/template.less
  themes/default/views/forms/EnrollmentGradesReport.php
  themes/default/views/reports/ElectronicDiary.php
Labels: hotfix, Melhoria

#451 Fix/sedsp imports
  .vscode/settings.json
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/mappers/ClassroomMapper.php
  app/modules/sedsp/models/TipoEnsinoConversionException.php
  app/modules/sedsp/usecases/ClassStudentsRelation/GetFormacaoClasseFromSEDUseCase.php
  app/modules/sedsp/usecases/ClassStudentsRelation/GetRelacaoClassesFromSEDUseCase.php
  app/modules/sedsp/usecases/Student/GetExibirFichaAlunoFromSEDUseCase.php
  app/modules/sedsp/views/default/index.php
Labels: hotfix

#455 Fix/sedsp
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/datasources/sed/Student/StudentSEDDataSource.php
  app/modules/sedsp/usecases/ClassStudentsRelation/GetFormacaoClasseFromSEDUseCase.php
  app/modules/sedsp/usecases/Student/GetExibirFichaAlunoFromSEDUseCase.php
Labels: hotfix

#460 Feat/delete enrollment alert
  app/controllers/EnrollmentController.php
  js/enrollment/form/_initialization.js
  themes/default/views/student/_form.php
Labels: Funcionalidade

#462 Fix/added where to filter only the classes imported
  app/modules/sedsp/views/default/index.php
Labels: hotfix

#466 Fix: corrections to student imports
  app/modules/sedsp/LogError.php
  app/modules/sedsp/SedspModule.php
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/mappers/ClassroomMapper.php
  app/modules/sedsp/mappers/StudentMapper.php
  app/modules/sedsp/usecases/ClassStudentsRelation/GetFormacaoClasseFromSEDUseCase.php
  app/modules/sedsp/usecases/ClassStudentsRelation/GetRelacaoClassesFromSEDUseCase.php
  app/modules/sedsp/usecases/School/GetEscolasFromSEDUseCase.php
  app/modules/sedsp/usecases/Student/GetExibirFichaAlunoFromSEDUseCase.php
  app/modules/sedsp/views/default/index.php
Labels: hotfix

#467 Fix: additional treatment for student not found
  app/modules/sedsp/mappers/ClassroomMapper.php
Labels: hotfix

#469 Fix: get classes based on the selected class
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/views/default/index.php
Labels: Funcionalidade
