Repository ipti/br.tag, pull requests merged in 2023-05, with the labels that each got.

#291 feature: class council from 6th to 9th grade and high school
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilHighSchool.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilSixNineYear.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#293 fix: corrections to class council minutes and enrollment report reports
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  themes/default/views/reports/EnrollmentPerClassroomReport.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilHighSchool.php
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncilSixNineYear.php
  themes/default/views/reports/index.php
Labels: Melhoria

#299 feature: quarterly follow up report
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  themes/default/img/reportsIcon/student_monitoring.svg
  themes/default/views/reports/buzios/headers/headBuziosIV.php
  themes/default/views/reports/buzios/quarterly/QuarterlyFollowUpReport.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#303 feature: evaluation follow up of students
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  themes/default/img/reportsIcon/monitoring_report.svg
  themes/default/views/reports/buzios/headers/headBuziosII.php
  themes/default/views/reports/buzios/quarterly/EvaluationFollowUpReport.php
  themes/default/views/reports/index.php
Labels: Funcionalidade

#308 refactor/add icon font
  sass/css/main.css
  sass/scss/_icons.scss
Labels: Melhoria

#310 fix/misalignment on the report screen
  CHANGELOG.md
  config.php
  css/reports.css
  themes/default/views/reports/index.php
Labels: hotfix

#313 fix/update user select
  CHANGELOG.md
  config.php
  themes/default/views/admin/_form.php
Labels: hotfix

#307 feature/regent teacher
  CHANGELOG.md
  app/controllers/ClassroomController.php
  app/controllers/ReportsController.php
  app/messages/pt_br/default.php
  app/migrations/3.21.44_add_regent_teacher/script.sql
  js/classroom/form/functions.js
  themes/default/views/classroom/_form.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportFirstYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportNurseryrIV.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreI.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportPreII.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportSecondYear.php
  themes/default/views/reports/buzios/quarterly/QuarterlyReportThreeYear.php
Labels: Funcionalidade

#321 fix: regent teacher
  js/classroom/form/functions.js
  themes/default/views/classroom/_form.php
Labels: hotfix

#322 Corrections in the sagres validation module
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/models/SagresValidations.php
  app/modules/sagres/views/default/index.php
Labels: hotfix

#329 Fix: query selection modified to select data up to the current day
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/models/SagresValidations.php
  app/modules/sagres/views/default/index.php
  css/sagres.css
Labels: hotfix

#331 Fix/corrections to enrollment and professional forms
  CHANGELOG.md
  app/modules/professional/views/default/_form.php
  config.php
  themes/default/css/template2.css
  themes/default/views/classes/classContents.php
  themes/default/views/classes/frequency.php
  themes/default/views/student/_form.php
Labels: hotfix

#330 Fix: Improved message for notifying absence of a teacher or curricular component for a class
  app/modules/sagres/models/SagresValidations.php
Labels: hotfix

#335 Fix: added filtering of students by year
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/models/SagresValidations.php
Labels: hotfix

#337 Fix: Correction of the approved student status
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix
