Repository ipti/br.tag, pull requests merged in 2023-10, with the labels that each got.

#470 Refactor/reports controller refactoring
  app/controllers/ReportsController.php
  app/repository/ReportsRepository.php
  themes/default/views/reports/ComplementarActivityAssistantByClassroomReport.php
  themes/default/views/reports/index.php
Labels: Melhoria

#471 Refactor/forms controller refactoring
  app/controllers/FormsController.php
  app/repository/FormsRepository.php
Labels: Melhoria

#479 Fix: correction in edcenso_city for sedsp
  app/modules/sedsp/mappers/StudentMapper.php
  app/modules/sedsp/usecases/Student/GetExibirFichaAlunoFromSEDUseCase.php
Labels: hotfix

#488 Fix/tree structure and recursion in BNCC endpoint
  app/extensions/bncc-import/BNCCImport.php
Labels: hotfix

#492 Fix/new code bugs
  app/controllers/ClassroomController.php
  app/extensions/Validator/SchoolIdentificationValidation.php
  app/extensions/Validator/SchoolStructureValidation.php
  app/modules/sagres/models/SagresValidations.php
  app/modules/sedsp/datasources/sed/Enrollment/EnrollmentSEDDataSource.php
  app/modules/sedsp/datasources/sed/SedDataSource.php
  app/modules/sedsp/models/Classroom/InConsultaTurmaClasse.php
  app/modules/sedsp/models/Classroom/InDiasDaSemana.php
  app/modules/sedsp/models/Classroom/InFormacaoClasse.php
  app/modules/sedsp/models/Classroom/InIncluirTurmaClasse.php
  app/modules/sedsp/models/Classroom/InNivelEnsino.php
  app/modules/sedsp/models/Enrollment/InExibirMatriculaClasseRA.php
  app/modules/sedsp/models/Enrollment/InInscricao.php
  app/modules/sedsp/models/Enrollment/InMatricula.php
  app/modules/sedsp/models/Enrollment/InMatricularAluno.php
  app/modules/sedsp/models/Enrollment/InscreverAluno.php
  app/modules/sedsp/models/OutHandleApiResult.php
  app/modules/sedsp/models/School/InEscola.php
  app/modules/sedsp/models/Student/InAluno.php
  app/modules/sedsp/models/Student/InCertidaoAntiga.php
  app/modules/sedsp/models/Student/InCertidaoNova.php
  app/modules/sedsp/models/Student/InConsultaRA.php
  app/modules/sedsp/models/Student/InDadosPessoais.php
  app/modules/sedsp/models/Student/InDeficiencia.php
  app/modules/sedsp/models/Student/InDocumentos.php
  app/modules/sedsp/models/Student/InEnderecoResidencial.php
  app/modules/sedsp/models/Student/InFichaAluno.php
  app/modules/sedsp/models/Student/InFiltrosNomes.php
  app/modules/sedsp/models/Student/InListarAlunos.php
  app/modules/sedsp/models/Student/InNivelEnsino.php
  app/modules/sedsp/models/Student/InRastreio.php
  app/modules/sedsp/models/Student/InRecursoAvaliacao.php
  app/modules/sedsp/models/Student/InResponsavelAluno.php
  app/modules/tag/components/adapter/Adapter.php
  app/modules/tag/models/ExportModel.php
  app/modules/tag/models/ImportModel.php
  js/admin/grades-structure.js
  js/enrollment/reportCard/_initialization.js
  themes/default/css/select2.css
  themes/default/css/template.css
  themes/default/css/template2.css
Labels: Melhoria

#506 Feat/tag students sync to sedsp
  app/controllers/StudentController.php
  app/migrations/2023-10-23_sedsp_sync/query.sql
  app/models/EdcensoCity.php
  app/models/StudentDocumentsAndAddress.php
  app/models/StudentIdentification.php
  app/modules/sedsp/SedspModule.php
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/datasources/sed/Enrollment/EnrollmentSEDDataSource.php
  app/modules/sedsp/datasources/sed/SedDataSource.php
  app/modules/sedsp/datasources/sed/Student/StudentSEDDataSource.php
  app/modules/sedsp/mappers/ClassroomMapper.php
  app/modules/sedsp/mappers/StudentMapper.php
  app/modules/sedsp/models/Enrollment/InExcluirMatricula.php
  app/modules/sedsp/models/Student/InAluno.php
  app/modules/sedsp/models/Student/InEnderecoResidencial.php
  app/modules/sedsp/models/Student/InManutencao.php
  app/modules/sedsp/models/Student/InRecursoAvaliacao.php
  app/modules/sedsp/models/Student/InTelefone.php
  app/modules/sedsp/usecases/AddStudentToSED.php
  app/modules/sedsp/usecases/Enrollment/ExcluirMatriculaFromSEDUseCase.php
  app/modules/sedsp/usecases/Student/UpdateFichaAlunoInTAGUseCase.php
  js/student/form/validations.js
  themes/default/views/student/_form.php
  themes/default/views/student/index.php
Labels: Funcionalidade
