Repository ipti/br.tag, pull requests merged in 2024-03, with the labels that each got.

#625 Fix: Correção na obtenção do CPF do estudante para o arquivo SAGRES:
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority

#630 Feat/no movement sagres
  CHANGELOG.md
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/index.php
  config.php
Labels: Funcionalidade, High priority, Aguardando review 1

#631 Feat/button alphabetic order
  CHANGELOG.md
  app/controllers/ClassroomController.php
  config.php
  js/classroom/form/_initialization.js
  js/classroom/form/functions.js
  themes/default/views/classroom/_form.php
Labels: Aguardando review 1, Aguardando review 2

#628 [Versão 3.71.112] Fix/class plan abilities view
  CHANGELOG.md
  app/controllers/CourseplanController.php
  app/messages/pt_br/default.php
  app/migrations/2024-02-27_course_plan_type/sql.sql
  app/models/CourseClass.php
  config.php
  js/courseplan/form/_initialization.js
  js/courseplan/form/functions.js
  sass/css/main.css
  sass/scss/_badge.scss
  sass/scss/_grid.scss
  sass/scss/_icons.scss
  themes/default/css/template.css
  themes/default/views/courseplan/form.php
Labels: Aguardando review 2

#619 Feat calendar surpassing year
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/controllers/ClassroomController.php
  app/migrations/2024-01-22_calendar_surpassing_year/sql
  app/models/Classroom.php
  app/models/GradeUnityPeriods.php
  app/models/Schedule.php
  app/modules/calendar/components/views/calendar.php
  app/modules/calendar/controllers/DefaultController.php
  app/modules/calendar/messages/pt_br/labels.php
  app/modules/calendar/models/Calendar.php
  app/modules/calendar/resources/common/css/layout.css
  app/modules/calendar/resources/common/js/calendar.js
  app/modules/timesheet/controllers/TimesheetController.php
  app/modules/timesheet/models/Schedule.php
  app/modules/timesheet/resources/common/js/timesheet.js
  app/repository/FormsRepository.php
  js/classes/class-contents/_initialization.js
  js/classes/class-contents/functions.js
  js/classes/frequency/_initialization.js
  js/classroom/form/functions.js
  themes/default/css/home.css
  themes/default/views/classes/classContents.php
  themes/default/views/classes/frequency.php
  themes/default/views/classroom/_form.php
  themes/default/views/timesheet/timesheet/index.php
  themes/default/views/wizard/configuration/classrooms.php
Labels: High priority, Aguardando review 2

#642 Fix/correction sagres 2024
  CHANGELOG.md
  app/modules/sagres/config.yml
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/SagresConsultModel.php
  config.php
  config.yml
Labels: hotfix, High priority

#637 [TCDA-240] Fix/load schedules by discipline
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
Labels: hotfix, High priority

#638 Feat: case added for class 22 and multi alias
  CHANGELOG.md
  config.php
  themes/default/views/forms/EnrollmentDeclarationReport.php
Labels: hotfix, Aguardando review 1

#640 Fix: gestor not edit calendar
  CHANGELOG.md
  app/modules/calendar/components/views/calendar.php
  config.php
  themes/default/views/layouts/fullmenu.php
Labels: hotfix

#639 Feat/warning missing content
  CHANGELOG.md
  app/composer.lock
  app/config/main.php
  app/controllers/SiteController.php
  app/models/Classroom.php
  app/modules/foods/resources/_initialization.js
  app/modules/foods/resources/functions.js
  app/modules/foods/resources/inventory/_initialization.js
  app/modules/foods/resources/inventory/functions.js
  app/modules/foods/resources/mealsOfWeek/_initialization.js
  app/modules/foods/resources/menuComponents.js
  app/modules/foods/resources/request/_initialization.js
  config.php
  js/site/index.js
  themes/default/css/home.css
  themes/default/views/site/index.php
Labels: Melhoria, Aguardando review 1, Aguardando review 2

#648 Fix/merenda escolar
  CHANGELOG.md
  app/modules/foods/resources/functions.js
  app/modules/foods/resources/menuComponents.js
  app/modules/foods/views/foodmenu/_form.php
  config.php
  sass/css/main.css
  sass/scss/_accordeon.scss
Labels: hotfix, Precisa de alterações

#651 Fix/no_notes
  CHANGELOG.md
  app/modules/wizard/controllers/ConfigurationController.php
  config.php
Labels: Aguardando review 2

#656 Feat/empty cpf students
  CHANGELOG.md
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/index.php
  config.php
Labels: Aguardando review 1, Aguardando review 2

#657 Feat/instructor frequency
  CHANGELOG.md
  app/models/Import.php
  config.php
  js/classes/frequency/_initialization_instructor.js
  themes/default/views/classes/frequencyInstructor.php
Labels: Aguardando review 1, Aguardando review 2

#659 Feat/added professional for different schools
  CHANGELOG.md
  app/models/Professional.php
  app/modules/professional/controllers/DefaultController.php
  config.php
Labels: Melhoria, Aguardando review 1, Aguardando review 2

#661 Fix/manager not authorized for school pdf
  CHANGELOG.md
  app/controllers/SchoolController.php
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority

#665 Feat/added professional for different schools
  app/modules/professional/controllers/DefaultController.php
Labels: hotfix, High priority, Aguardando review 1, Aguardando review 2

#664 Fix: correction in inep_id
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, High priority, Aguardando review 1

#668 Fix: correction in description class
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority, Aguardando review 2
