Repository ipti/br.tag, pull requests merged in 2024-05, with the labels that each got.

#702 Fix/new correction and validation sagres
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/_form.php
  app/modules/sagres/views/default/index.php
  config.php
Labels: hotfix

#703 fix: allow delete matrix
  app/modules/curricularmatrix/controllers/CurricularmatrixController.php
  app/modules/curricularmatrix/resources/common/js/curricularmatrix.js
  js/datatables/init.js
  themes/default/views/curricularmatrix/curricularmatrix/index.php
Labels: hotfix, High priority, Aguardando review 1, Aguardando review 2

#709 Fix/sagres dates and cpfs
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/inconsistencys.php
Labels: hotfix, High priority

#674 Fix/counting faults
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority, Aguardando review 1

#700 [TCDA-380] Fix/ Add Nationality Origin To StudentFile
  CHANGELOG.md
  app/migrations/2024-06-05_student_file_nationality/sql.sql
  config.php
  themes/default/views/forms/StudentFileForm.php
Labels: hotfix, Pronto para merge

#705 [TCDA - 392] Fix/Scrollbar Visualization
  CHANGELOG.md
  config.php
  js/classes/frequency/_initialization.js
  sass/css/main.css
  themes/default/css/template2.css
Labels: hotfix, Pronto para merge

#708 [TCDA-425] Fix/reports-correction
  themes/default/views/reports/buzios/quarterly/QuarterlyClassCouncil.php
Labels: hotfix, Pronto para merge

#711 [TCDA-394] fix/do-not-fill-grade
  CHANGELOG.md
  app/controllers/GradesController.php
  config.php
Labels: hotfix, Pronto para merge

#712 [TCDA-422] Fix/layout problem
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
  js/classes/class-contents/functions.js
Labels: hotfix, High priority, Pronto para merge

#713 [TCDA-380] Fix/ Report Style
  CHANGELOG.md
  app/migrations/2024-05-13_insert_inepid_classroom/sql.sql
  config.php
  themes/default/views/reports/IncompatibleStudentAgeByClassroomReport.php
Labels: hotfix, Pronto para merge

#714 [TCDA-436] Feat: students-class-report
  CHANGELOG.md
  app/migrations/2024-05-14_students_class_report/default.sql
Labels: hotfix, Pronto para merge

#715 [TCDA-157] Fix/erro-message-educacenso
  CHANGELOG.md
  app/controllers/CensoController.php
  config.php
Labels: hotfix, Pronto para merge

#716 Fix: correction in id student identification
  CHANGELOG.md
  config.php
  js/student/form/validations.js
  themes/default/js/util.js
Labels: hotfix, High priority, Pronto para merge

#717 [TCDA-446] Feat/date-final
  CHANGELOG.md
  app/components/DatePickerWidget.php
  config.php
  js/school/form/_initialization.js
  themes/default/views/school/_form.php
Labels: hotfix, Pronto para merge

#720 [TCDA-437] Feat/validator-register-civil
  CHANGELOG.md
  app/models/StudentDocumentsAndAddress.php
  config.php
Labels: hotfix, Pronto para merge

#721 [TCDA-426] Fix/empty_users_fk_istructor_identification
  CHANGELOG.md
  app/controllers/InstructorController.php
  config.php
Labels: hotfix, Pronto para merge

#727 Fix/duplicate cpf student count
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, High priority

#719 [TCDA-475] Fix/erro-educacenso-stage
  app/controllers/CensoController.php
  app/extensions/Validator/ClassroomValidation.php
  app/migrations/2024-05-21-update-classroom-modality-set-100/2024-05-21-update-classroom-modality-set-100.sql
  themes/default/views/classroom/_form.php
Labels: hotfix, High priority, Pronto para merge

#732 Feat: added new modality
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, High priority
