Repository ipti/br.tag, pull requests merged in 2024-07, with the labels that each got.

#766 fix: dia da semana e remoção de caracteres especiais
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, High priority

#768 Fix/sagres v5
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, Pronto para merge

#751 [TCDA-526] Fix/Instructor Imported Without User
  CHANGELOG.md
  app/controllers/InstructorController.php
  app/domain/admin/usecases/importInstructorUserUseCase.php
  app/modules/tag/models/ImportModel.php
Labels: High priority, Pronto para merge

#758 [TCDA - 569] fix: dynamic width for lesson plans
  sass/scss/components/_field-multiselect.scss
Labels: hotfix, Pronto para merge

#760 Feat/csv exports
  CHANGELOG.md
  app/controllers/AdminController.php
  config.php
  instance.php
  themes/default/views/admin/exports.php
  themes/default/views/admin/index.php
Labels: Funcionalidade, Pronto para merge

#763 Fix/frequency multi classes
  CHANGELOG.md
  app/components/utils/TagUtils.php
  app/controllers/ClassesController.php
  config.php
  js/classes/class-contents/_initialization.js
  js/classes/frequency/_initialization.js
  js/classes/frequency/_initialization_instructor.js
  js/enrollment/form/_initialization.js
  js/enrollment/form/validations.js
  js/student/form/_initialization.js
  js/student/form/validations.js
  themes/default/views/enrollment/_form.php
  themes/default/views/student/_form.php
Labels: hotfix, Pronto para merge

#787 [TCDA-634] Fix: Inconsistency for students born in the current year
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix
