Repository ipti/br.tag, pull requests merged in 2024-11, with the labels that each got.

#849 [TCDA-705]Feat/Add enrollment status label to Grades view
  CHANGELOG.md
  app/domain/grades/usecases/GetStudentGradesByDisciplineUsecase.php
  app/models/Classroom.php
  app/modules/classdiary/services/StudentService.php
  app/modules/classdiary/views/default/_frequencyElementMobile.php
  js/grades/functions.js
Labels: Pronto para merge

#853 Fix/Student Frequency New Classroom
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/controllers/StudentController.php
  app/messages/pt_br/default.php
  app/migrations/2024-10-14_enrollment_date_student_enrollment/sql.sql
  app/models/StudentEnrollment.php
  config.php
  js/classes/frequency/_initialization.js
  js/classes/frequency/_initialization_instructor.js
Labels: Pronto para merge

#857 Fix/change class contents schedule
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/migrations/2024-10-23_remove_class_contents_schedule_fk/default.sql
  app/models/ClassContents.php
  app/modules/calendar/controllers/DefaultController.php
  config.php
Labels: Pronto para merge

#860 feat/hide_instructor_frequency_and_classContent
  app/components/FeaturesComponent.php
  app/migrations/2024-26-10_hide_frequency_and_classContent/insert_instance_config.sql
  themes/default/views/layouts/fullmenu.php
Labels: Aguardando review 1

#862 Fix/hide log professor
  app/controllers/SiteController.php
  themes/default/views/site/index.php
Labels: Pronto para merge

#864 Fix/add classes count on class contents
  CHANGELOG.md
  app/controllers/ClassesController.php
  js/classes/class-contents/functions.js
  js/classes/class-contents/validateFunctions.js
  themes/default/views/classes/classContents.php
  themes/default/views/classes/validateClassContents.php
Labels: Aguardando review 2

#876 adicionado formulada média para o cálculo da recuperação final
  CHANGELOG.md
  app/controllers/AdminController.php
  app/controllers/GradesController.php
  app/domain/grades/usecases/CalculateFinalMediaUsecase.php
  app/domain/grades/usecases/CalculateNumericGradeUsecase.php
  app/domain/grades/usecases/ChageStudentStatusByGradeUsecase.php
  app/migrations/2024-18-11_final_recovery_avarage_formula/2024-18-11_final_recovery_avarage_formula.sql
  config.php
  js/admin/grades-structure.js
  themes/default/views/admin/gradesStructure.php
Labels: Pronto para merge

#880 Fix/class contents report
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/controllers/ReportsController.php
  app/models/ClassContents.php
  app/models/Classroom.php
  app/models/StudentEnrollment.php
  app/modules/classdiary/services/ClassesService.php
  config.php
  instance.php
  js/classes/class-contents/_initialization.js
  sass/css/main.css
  themes/default/views/admin/manageUsers.php
  themes/default/views/reports/ClassContentsReport.php
Labels: Pronto para merge

#872 corrigidos TCDAs 744, 745 e 746
  CHANGELOG.md
  app/controllers/AdminController.php
  app/controllers/ReportsController.php
  app/migrations/2024-11-10_classroom_qtd_students_9º_ano/sql
  config.php
  themes/default/views/reports/NumberStudentsPerClassroomReport.php
Labels: Pronto para merge

#859 Fix/unity recovery
  CHANGELOG.md
  config.php
  js/admin/grades-structure.js
Labels: Pronto para merge

#871 fix/save-structure
  app/controllers/AdminController.php
Labels: Aguardando review 1
