Repository ipti/br.tag, pull requests merged in 2024-10, with the labels that each got.

#819 Fix/ Delay on courseplan loading
  CHANGELOG.md
  app/modules/courseplan/controllers/CourseplanController.php
  app/modules/courseplan/resources/_initialization.js
  app/modules/courseplan/views/courseplan/_table_pendingPlans.php
  app/modules/courseplan/views/courseplan/pendingPlans.php
Labels: Pronto para merge

#838 Fix/aee record pagination
  CHANGELOG.md
  app/modules/aeerecord/controllers/DefaultController.php
Labels: Pronto para merge

#839 Fix/final recovery modality
  app/controllers/AdminController.php
  app/domain/grades/usecases/CalculateNumericGradeUsecase.php
  instance.php
Labels: Aguardando review 1

#840 Feat/unified frequency
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/migrations/2024-04-10_add_unified_frequency_column/sql.sql
  app/models/EdcensoStageVsModality.php
  app/modules/classdiary/controllers/DefaultController.php
  app/modules/classdiary/services/ClassesService.php
  app/modules/classdiary/services/StudentService.php
  app/modules/classdiary/views/default/_frequencyElementMobile.php
  app/modules/stages/controllers/DefaultController.php
  app/modules/stages/views/default/_form.php
  config.php
  js/classes/class-contents/_initialization.js
  js/classes/class-contents/functions.js
Labels: Funcionalidade, High priority, Aguardando review 1, Precisa de alterações

#848 [TCDA-699] Feat/Frequency for transfered students
  CHANGELOG.md
  app/controllers/ClassesController.php
  js/classes/frequency/_initialization.js
Labels: Aguardando review 1

#851 fix/food_menu_access
  CHANGELOG.md
  app/modules/foods/views/foodmenu/index.php
  instance.php
Labels: Pronto para merge

#855 Fix/calculate final recovery eja
  CHANGELOG.md
  app/domain/grades/usecases/CalculateFinalMediaUsecase.php
  app/domain/grades/usecases/CalculateNumericGradeUsecase.php
  config.php
  instance.php
  js/grades/_initialization.js
  js/grades/functions.js
Labels: Pronto para merge
