Repository ipti/br.tag, pull requests merged in 2024-06, with the labels that each got.

#737 Fix/new sagres rules
  app/models/Professional.php
  app/modules/professional/views/default/_form.php
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, High priority

#740 Fix/new sagres rules
  CHANGELOG.md
  app/migrations/2024-06-06_new_rules_sagres/sql.sql
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority

#724 Fix/error-pdf-studentfileform
  CHANGELOG.md
  config.php
  themes/default/views/forms/StudentFileForm.php
Labels: hotfix, Pronto para merge

#730 Feat/edcenso 2024
  CHANGELOG.md
  app/controllers/CensoController.php
  app/extensions/Validator/SchoolIdentificationValidation.php
  app/extensions/Validator/SchoolStructureValidation.php
  app/libraries/Educacenso/Register10.php
  app/libraries/Educacenso/Register20.php
  app/libraries/Educacenso/Register50.php
  app/libraries/Educacenso/Register60.php
  app/messages/pt_br/default.php
  app/migrations/2024-05-27_edcenso_2024/edcenso_alias
  app/migrations/2024-05-27_edcenso_2024/other_tables
  app/models/SchoolStructure.php
  app/models/StudentEnrollment.php
  app/repository/ReportsRepository.php
  config.php
  themes/default/views/school/_form.php
  themes/default/views/student/_form.php
Labels: Funcionalidade, Pronto para merge

#731 [TCDA-464] fix/delete-enrollmet
  CHANGELOG.md
  config.php
  themes/default/views/student/_form.php
Labels: hotfix, Pronto para merge

#734 Fix/error-educacenso-duplicated
  CHANGELOG.md
  app/controllers/CensoController.php
  config.php
Labels: hotfix, Pronto para merge

#739 Fix/correction-datepicker-last
  CHANGELOG.md
  app/components/DatePickerWidget.php
  config.php
Labels: hotfix, Melhoria, Precisa de alterações

#735 [TCDA-523] fix/error-classContents
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
Labels: hotfix, Pronto para merge

#754 Feat/teacher classrons list
  CHANGELOG.md
  app/controllers/InstructorController.php
  config.php
  js/instructor/form/functions.js
  sass/css/main.css
  themes/default/views/instructor/_form.php
Labels: Funcionalidade, Pronto para merge

#749 Feat: new inconsistency for Management Unit
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/inconsistencys.php
  config.php
Labels: Funcionalidade, Pronto para merge

#738 Feat/timesheet turn
  CHANGELOG.md
  app/migrations/2024-06-03_timesheet_turn/sql
  app/models/Schedule.php
  app/modules/timesheet/controllers/TimesheetController.php
  app/modules/timesheet/models/Schedule.php
  app/modules/timesheet/resources/common/js/timesheet.js
  config.php
Labels: hotfix, Pronto para merge

#741 [TCDA-533] Fix/transfered student frequency
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
  js/classes/frequency/_initialization.js
Labels: hotfix, Pronto para merge

#745 [TCDA-380] Fix/enrollment report nationality
  CHANGELOG.md
  app/migrations/2024-06-10_enrollment_classroom_nationality/sql.sql
  config.php
  themes/default/views/reports/EnrollmentPerClassroomReport.php
Labels: hotfix, Pronto para merge

#755 Fix/stage edcenso field to name
  CHANGELOG.md
  app/modules/stages/controllers/DefaultController.php
  app/modules/stages/resources/_initialization.js
  app/modules/stages/views/default/_form.php
  config.php
Labels: hotfix, Pronto para merge

#718 [TCDA-463] Fix/class specification report
  CHANGELOG.md
  app/repository/ReportsRepository.php
  config.php
  js/reports/ElectronicDiary/index.js
Labels: hotfix, Pronto para merge

#757 Fix/head school required
  CHANGELOG.md
  config.php
  js/school/form/validations.js
Labels: hotfix, Pronto para merge
