Repository ipti/br.tag, pull requests merged in 2024-02, with the labels that each got.

#607 Fix/correction date attendance
  app/modules/professional/controllers/DefaultController.php
  app/modules/professional/views/default/_form.php
Labels: hotfix, High priority, Aguardando review 2

#606 feat/add value 5 in array scholarity
  CHANGELOG.md
  config.php
  themes/default/views/student/_form.php
Labels: Aguardando review 1

#609 Feat/add report card concept grades
  app/controllers/EnrollmentController.php
  app/controllers/GradesController.php
  config.php
  js/enrollment/gradesRelease/_initialization.js
  js/enrollment/reportCard/_initialization.js
  js/enrollment/reportCard/functions.js
  themes/default/views/enrollment/reportCard.php
Labels: Aguardando review 1

#608 Feat/foodmenu report
  app/controllers/ReportsController.php
  app/migrations/2023-12-22_inserts_foods/sql.sql
  app/migrations/2024-01-26_food_menu_report/sql.sql
  app/modules/foods/FoodsModule.php
  app/modules/foods/controllers/FoodmenuController.php
  app/modules/foods/controllers/ReportsController.php
  app/modules/foods/models/FoodMenu.php
  app/modules/foods/resources/_initialization.js
  app/modules/foods/resources/functions.js
  app/modules/foods/resources/menuComponents.js
  app/modules/foods/services/FoodMenuService.php
  app/modules/foods/usecases/CreateFoodMenuRelations.php
  app/modules/foods/usecases/GetFoodMenu.php
  app/modules/foods/usecases/GetMealType.php
  app/modules/foods/usecases/GetMelsOfWeek.php
  app/modules/foods/usecases/GetNutritionalValue.php
  app/modules/foods/views/foodMenu/_form.php
  app/modules/foods/views/foodMenu/index.php
  app/modules/foods/views/foodmenu/_form.php
  app/modules/foods/views/foodmenu/index.php
  app/modules/foods/views/reports/FoodMenuReport.php
  app/modules/foods/views/reports/ShoppingListReport.php
  themes/default/views/reports/FoodMenu.php
Labels: Precisa de alterações

#602 Feat/sagres 2024
  app/migrations/2024-02-01_adjust_sagres_2024/default.sql
  app/models/EdcensoDiscipline.php
  app/modules/lunch/models/Meal.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/soap/Educacao.xsd
  themes/default/views/classroom/_form.php
  themes/default/views/lunch/lunch/_form.php
Labels: hotfix, Aguardando review 1, Aguardando review 2

#605 feat/ removed in field input (*)
  CHANGELOG.md
  config.php
  themes/default/views/classes/classContents.php
Labels: Aguardando review 1, Aguardando review 2

#613 Fix/import student data from sedsp
  app/modules/sedsp/usecases/Student/UpdateFichaAlunoInTAGUseCase.php
Labels: hotfix, Aguardando review 1, Aguardando review 2

#616 Feat/md5 to bcrypt
  CHANGELOG.md
  app/components/PasswordHasher.php
  app/components/UserIdentity.php
  app/controllers/AdminController.php
  app/controllers/AdministratorController.php
  app/controllers/InstructorController.php
  app/migrations/2024-02-06_md5_to_bcrypt/default.sql
  app/models/Users.php
Labels: Melhoria, Aguardando review 1, Aguardando review 2

#623 Fix/synchronize sedsp student data
  CHANGELOG.md
  app/modules/sedsp/controllers/DefaultController.php
  app/modules/sedsp/mappers/StudentMapper.php
  app/modules/sedsp/usecases/Student/UpdateFichaAlunoInTAGUseCase.php
Labels: hotfix, High priority

#618 Fix/food inventory style
  CHANGELOG.md
  app/modules/foods/resources/inventory/_initialization.js
  app/modules/foods/resources/inventory/functions.js
  app/modules/foods/views/foodInventory/_form.php
  app/modules/foods/views/foodinventory/_form.php
  config.php
  sass/css/main.css
  sass/scss/_button.scss
  sass/scss/_grid.scss
  sass/scss/_helpers.scss
  sass/scss/_lists.scss
  sass/scss/_separator.scss
Labels: wontfix

#629 Fix/schema sagres 2024
  CHANGELOG.md
  app/modules/sagres/soap/Genericos.xsd
  app/modules/sagres/soap/TabelasInternas.xsd
  app/modules/sagres/soap/metadata/genericosMetadata/NaContratoTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NaConvenioTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NaProcLicitatorioTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroAtoQueNomeGestorTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroAtoQueNomeOrdenadorTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroDecretoTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroLdoTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroLeiAltePpaTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroLeiPpaTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/NumeroLeiQueAutorizouTType.yml
  app/modules/sagres/soap/metadata/genericosMetadata/OrgaoRespAtaRegPrecosTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/AlunoTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/AtendimentoTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/CabecalhoTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/CardapioTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/DiretorTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/Educacao.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/EducacaoTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/EscolaTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/HorarioTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/MatriculaTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/ProfissionalTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/SerieTType.yml
  app/modules/sagres/soap/metadata/sagresEduMetadata/TurmaTType.yml
  app/modules/sagres/soap/src/sagresEdu/AlunoTType.php
  app/modules/sagres/soap/src/sagresEdu/EducacaoTType.php
  app/modules/sagres/soap/src/sagresEdu/EscolaTType.php
  app/modules/sagres/soap/src/sagresEdu/MatriculaTType.php
  app/modules/sagres/soap/src/sagresEdu/ProfissionalTType.php
  config.php
Labels: hotfix
