Repository ipti/br.tag, pull requests merged in 2024-04, with the labels that each got.

#647 Feat/food notice
  CHANGELOG.md
  app/modules/foods/views/foodinventory/_form.php
  config.php
  sass/css/main.css
Labels: hotfix

#677 Fix/add lunch unities [Versão 3.77.132]
  CHANGELOG.md
  app/migrations/2024-06-04_add_lunch_unities/sql.sql
  config.php
  themes/default/views/lunch/stock/index.php
Labels: hotfix, Pronto para merge

#675 Feat/school management signature
  CHANGELOG.md
  themes/default/views/forms/EnrollmentDeclarationReport.php
Labels: Funcionalidade, Pronto para merge

#673 Fix/date corrections
  CHANGELOG.md
  app/controllers/StudentController.php
  app/models/StudentDocumentsAndAddress.php
  app/modules/sagres/models/SagresConsultModel.php
  config.php
  js/school/form/validations.js
  themes/default/views/instructor/_form.php
  themes/default/views/school/_form.php
  themes/default/views/student/_form.php
Labels: hotfix, Pronto para merge

#676 Fix/instructor frequency [Versão 3.77.131]
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
  js/classes/frequency/_initialization.js
  js/classes/frequency/_initialization_instructor.js
  sass/css/main.css
  sass/scss/_accordeon.scss
  sass/scss/_helpers.scss
Labels: hotfix

#682 Feat: returns active schools
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: Funcionalidade, High priority

#667 Fix: Reordered parameters in getSchedulesFromMajorStage method
  CHANGELOG.md
  app/controllers/ClassesController.php
Labels: hotfix, High priority, Pronto para merge

#687 Fix: date range correction
  CHANGELOG.md
  config.php
  themes/default/views/school/_form.php
Labels: hotfix, High priority, Pronto para merge

#688 Fix: correction in select date for birthday
  CHANGELOG.md
  js/student/form/validations.js
Labels: hotfix, High priority, Pronto para merge

#691 Fix/sagres componentes curriculares
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority, Pronto para merge

#696 Fix/class sagres inconsistency
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority, Pronto para merge

#683 Fix/class turn
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, Pronto para merge

#693 Fix/datepicker pt br
  CHANGELOG.md
  app/components/DatePickerWidget.php
  config.php
  themes/default/views/instructor/_form.php
  themes/default/views/school/_form.php
  themes/default/views/student/_form.php
Labels: Melhoria, Pronto para merge

#679 Fix/inconsistency lunch
  CHANGELOG.md
  app/migrations/2024-04-12_inconsistency_lunch/default.sql
  app/modules/lunch/messages/pt_br/lunch.php
  app/modules/lunch/models/Meal.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/models/ValidationSagresModel.php
  app/modules/sagres/views/default/inconsistencys.php
Labels: hotfix, Pronto para merge

#686 Fix/stock [Versão 3.77.135]
  CHANGELOG.md
  app/modules/lunch/controllers/StockController.php
  app/modules/lunch/models/Item.php
  themes/default/views/lunch/stock/index.php
Labels: hotfix, Aguardando review 1

#689 Fix/instructor frequency
  app/controllers/ClassesController.php
  js/classes/frequency/_initialization_instructor.js
Labels: Aguardando review 1
