Repository ipti/br.tag, pull requests merged in 2024-01, with the labels that each got.

#577 Fix: sagres-generation
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix

#585 Feat/sagres 2024
  app/models/EdcensoDiscipline.php
  app/modules/lunch/models/Meal.php
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/soap/Educacao.xsd
  themes/default/views/classroom/_form.php
Labels: Melhoria

#600 Fix: year of generation of the file changed to the one selected in th…
  app/modules/sagres/controllers/DefaultController.php
  app/modules/sagres/views/default/index.php
Labels: hotfix, High priority

#596 feat/add year to all reports
  themes/default/views/reports/BFReport.php
  themes/default/views/reports/ClassroomWithoutInstructorRelationReport.php
  themes/default/views/reports/CnsReport.php
  themes/default/views/reports/ComplementarActivityAssistantByClassroomReport.php
  themes/default/views/reports/DisciplineAndInstructorRelationReport.php
  themes/default/views/reports/EducationalAssistantPerClassroomReport.php
  themes/default/views/reports/EnrollmentComparativeAnalysisReport.php
  themes/default/views/reports/EnrollmentStatisticsByYearReport.php
  themes/default/views/reports/IncompatibleStudentAgeByClassroomReport.php
  themes/default/views/reports/InstructorsPerClassroomReport.php
  themes/default/views/reports/NumberOfClassesPerSchool.php
  themes/default/views/reports/NumberOfStudentsEnrolledPerPeriod.php
  themes/default/views/reports/NumberStudentsPerClassroomReport.php
  themes/default/views/reports/OutOfTownStudentsReport.php
  themes/default/views/reports/ReportOfStudentsBenefitingFromTheBF.php
  themes/default/views/reports/SchoolProfessionalNumberByClassroomReport.php
  themes/default/views/reports/StatisticalData.php
  themes/default/views/reports/StudentByClassroomReport.php
  themes/default/views/reports/StudentCpfRgNis.php
  themes/default/views/reports/StudentInstructorNumbersRelationReport.php
  themes/default/views/reports/StudentPendingDocument.php
  themes/default/views/reports/StudentSpecialFood.php
  themes/default/views/reports/StudentsBetween5And14YearsOldReport.php
  themes/default/views/reports/StudentsByClassroomReport.php
  themes/default/views/reports/StudentsInAlphabeticalOrderRelationReport.php
  themes/default/views/reports/StudentsUsingSchoolTransportationRelationReport.php
  themes/default/views/reports/StudentsWithDisabilitiesPerClassroom.php
  themes/default/views/reports/StudentsWithDisabilitiesPerSchool.php
  themes/default/views/reports/StudentsWithDisabilitiesRelationReport.php
  themes/default/views/reports/TeachersBySchool.php
  themes/default/views/reports/TeachersByStage.php
  themes/default/views/reports/TotalNumberOfStudentsEnrolled.php
  themes/default/views/reports/TransferReport.php
Labels: Aguardando review 2
