Repository ipti/br.tag, pull requests merged in 2024-08, with the labels that each got.

#781 [TCDA-609] Fix/Course Plan Loading Delay
  CHANGELOG.md
  app/controllers/AdminController.php
  app/modules/courseplan/controllers/CourseplanController.php
  app/modules/courseplan/resources/_initialization.js
  app/modules/courseplan/views/courseplan/_table.php
  app/modules/courseplan/views/courseplan/index.php
  config.php
Labels: Pronto para merge

#782 fix/teachers_by_school_report
  CHANGELOG.md
  app/repository/ReportsRepository.php
  config.php
Labels: Pronto para merge

#788 Feat/new recovery calculation
  CHANGELOG.md
  app/controllers/AdminController.php
  app/controllers/ReportCardController.php
  app/domain/admin/usecases/UpdateGradeJustOneStructUsecase.php
  app/domain/admin/usecases/UpdateGradePartialRecoveryUsecase.php
  app/domain/grades/usecases/CalculateFinalMediaUsecase.php
  app/domain/grades/usecases/CalculateNumericGradeUsecase.php
  app/domain/grades/usecases/ChageStudentStatusByGradeUsecase.php
  app/domain/grades/usecases/GetStudentGradesByDisciplineUsecase.php
  app/migrations/2024-17-07_new_recovery_calculation/sql.sql
  app/models/GradeResults.php
  app/repository/FormsRepository.php
  app/repository/ReportsRepository.php
  config.php
  js/admin/grades-structure.js
  js/grades/_initialization.js
  js/grades/functions.js
  themes/default/views/admin/gradesStructure.php
  themes/default/views/forms/EnrollmentGradesReport.php
Labels: Pronto para merge

#790 Fix/rename column type to methodology
  CHANGELOG.md
  app/migrations/2024-07-31_change_courseplan_inputnames/sql.sql
  app/models/CourseClass.php
  app/modules/courseplan/controllers/CourseplanController.php
  app/modules/courseplan/resources/_initialization.js
  app/modules/courseplan/resources/functions.js
  app/modules/courseplan/views/courseplan/_form.php
  config.php
  themes/default/css/template.css
Labels: Pronto para merge

#791 Feat/create aee record
  CHANGELOG.md
  app/config/main.php
  app/migrations/2024-07-23_create_student_aee_report/default.sql
  app/modules/aeerecord/AeerecordModule.php
  app/modules/aeerecord/controllers/DefaultController.php
  app/modules/aeerecord/controllers/ReportsController.php
  app/modules/aeerecord/models/StudentAeeRecord.php
  app/modules/aeerecord/resources/_initialization.js
  app/modules/aeerecord/resources/functions.js
  app/modules/aeerecord/views/default/_form.php
  app/modules/aeerecord/views/default/admin.php
  app/modules/aeerecord/views/default/create.php
  app/modules/aeerecord/views/default/index.php
  app/modules/aeerecord/views/default/update.php
  app/modules/aeerecord/views/reports/aeeRecordReport.php
  config.php
  sass/css/main.css
  themes/default/views/layouts/fullmenu.php
  themes/default/views/reports/EnrollmentStatisticsByYearReport.php
Labels: Pronto para merge

#764 [TCDA-534] Fix/Student Transfered New Enrollment
  CHANGELOG.md
  app/controllers/ClassesController.php
  app/controllers/StudentController.php
  app/messages/pt_br/default.php
  app/migrations/2024-06-28_reenrollment_student/sql.sql
  app/models/StudentEnrollment.php
  config.php
  js/classes/frequency/_initialization.js
  js/enrollment/form/functions.js
  js/enrollment/form/validations.js
  themes/default/views/enrollment/_form.php
  themes/default/views/student/_form.php
Labels: Pronto para merge

#776 Fix/courseplan batchclassroom
  app/controllers/ClassesController.php
  app/controllers/ClassroomController.php
  app/migrations/2024-07-11_courseplan_typecolumn_increase/sql
  app/models/CourseClass.php
  app/modules/courseplan/controllers/CourseplanController.php
  js/classes/class-contents/functions.js
Labels: Pronto para merge

#802 Fix/sagres v6
  .php-cs-fixer.cache
  CHANGELOG.md
  app/export/SagresEdu/File_LOCALHOST/Educacao.zip
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/index.php
  config.php
  css/sagres.css
Labels: hotfix, Melhoria, Pronto para merge

#798 fix/Food Inventory Expiration Date
  CHANGELOG.md
  app/modules/foods/controllers/FoodinventoryController.php
  app/modules/foods/models/FoodInventory.php
  app/modules/foods/resources/inventory/_initialization.js
  app/modules/foods/views/foodinventory/_form.php
  config.php
Labels: hotfix, Pronto para merge

#799 Fix/Search input disabled
  CHANGELOG.md
  app/modules/courseplan/resources/_initialization.js
  app/modules/courseplan/resources/functions.js
  app/modules/courseplan/views/courseplan/_table.php
  js/courseplan/form/functions.js
Labels: hotfix, Pronto para merge

#796 Fix/report electronic diary data
  CHANGELOG.md
  app/models/GradeResults.php
  app/repository/ReportsRepository.php
  js/admin/grades-structure.js
  js/reports/ElectronicDiary/index.js
Labels: Pronto para merge

#797 Fix/aee record permissions
  CHANGELOG.md
  app/modules/aeerecord/controllers/DefaultController.php
  app/modules/aeerecord/views/default/admin.php
  config.php
  themes/default/views/layouts/fullmenu.php
Labels: Pronto para merge

#805 Feat/increase maximum number of characters in fields aee
  CHANGELOG.md
  app/migrations/2024-20-08_change_sudent_aee_record/sql.sql
  app/modules/aeerecord/models/StudentAeeRecord.php
  app/modules/aeerecord/views/default/_form.php
Labels: Pronto para merge

#810 Fix/sagres v7
  app/modules/sagres/models/SagresConsultModel.php
Labels: hotfix, Pronto para merge

#804 Feat/enrich stage creation
  app/composer.lock
  app/modules/courseplan/controllers/CourseplanController.php
  app/modules/courseplan/views/courseplan/_table.php
  app/modules/courseplan/views/courseplan/index.php
  app/modules/stages/controllers/DefaultController.php
  app/modules/stages/resources/_initialization.js
  app/modules/stages/views/default/_form.php
  app/modules/stages/views/default/index.php
Labels: Pronto para merge

#811 Sagres v8
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: hotfix, High priority
