Repository ipti/br.tag, pull requests merged in 2025-04, with the labels that each got.

#955 Fix/electronicdiary grade report
  CHANGELOG.md
  app/controllers/ReportsController.php
  app/repository/ReportsRepository.php
  config.php
  js/reports/ElectronicDiary/index.js
  themes/default/views/reports/ElectronicDiary.php
Labels: Pronto para merge

#964 Fix/remove school admission date
  CHANGELOG.md
  app/controllers/EnrollmentController.php
  app/controllers/StudentController.php
  app/messages/pt_br/default.php
  app/migrations/2025-29-03_drop_school_admission_date/drop.sql
  app/migrations/2025-29-03_drop_school_admission_date/view.sql
  app/models/StudentEnrollment.php
  js/enrollment/form/validations.js
  js/student/form/validations.js
  themes/default/views/enrollment/_form.php
  themes/default/views/forms/StudentFileForm.php
  themes/default/views/student/_form.php
Labels: High priority, Pronto para merge

#966 [TCDA-947] Fix/update relation search in model & docs
  CHANGELOG.md
  app/controllers/ClassroomController.php
  app/models/Classroom.php
Labels: Pronto para merge

#970 [TCDA-950] Fix/class diary get class contents
  CHANGELOG.md
  app/modules/classdiary/services/ClassesService.php
Labels: Pronto para merge

#968 fix/adjust filter on add substitute instructor view
  CHANGELOG.md
  app/modules/timesheet/controllers/TimesheetController.php
  config.php
Labels: hotfix, Pronto para merge

#934 Feat/add stages food menu
  CHANGELOG.md
  app/migrations/2025-19-02-create_food_menu_vs_edcenso_stage_vs_modality/2025-19-02-create_food_menu_vs_edcenso_stage_vs_modality.sql
  app/modules/foods/controllers/FoodmenuController.php
  app/modules/foods/controllers/ReportsController.php
  app/modules/foods/models/FoodMenuVsEdcensoStageVsModality.php
  app/modules/foods/resources/functions.js
  app/modules/foods/resources/mealsOfWeek/_initialization.js
  app/modules/foods/services/FoodMenuService.php
  app/modules/foods/views/foodmenu/_form.php
  app/modules/foods/views/foodmenu/update.php
  app/modules/foods/views/foodmenu/viewlunch.php
  app/modules/foods/views/reports/FoodMenuReport.php
  config.php
Labels: Funcionalidade, Pronto para merge

#977 Fix/save instructor frequency
  CHANGELOG.md
  app/migrations/2025-17-04_instructor_faults/sql.sql
  js/instructor/frequency.js
Labels: Aguardando review 1, Aguardando review 2

#983 Fix/sagres food
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
  docker-compose.yml
  instance.php
Labels: High priority, Aguardando review 1, Aguardando review 2
