Repository ipti/br.tag, pull requests merged in 2025-05, with the labels that each got.

#986 [TAG25-37] Fix/Change_metodology_column_type
  CHANGELOG.md
  app/migrations/2025-29-04_change_methodology_cc/sql.sql
  app/models/CourseClass.php
  app/modules/courseplan/resources/functions.js
  config.php
Labels: Aguardando review 1, Pronto para merge

#974 [Tag25-18] Fix: Class contents not registered
  CHANGELOG.md
  app/modules/classdiary/services/ClassesService.php
  app/modules/classdiary/usecases/GetClassContents.php
  app/modules/classdiary/usecases/SaveClassContents.php
  app/modules/classdiary/views/default/classDiary.php
  config.php
Labels: Pronto para merge

#985 fix/ correct inconsistency messages
  app/modules/sagres/models/SagresConsultModel.php
  app/modules/sagres/views/default/inconsistencys.php
Labels: High priority, Pronto para merge

#991 Fix/division by zero reports controller
  CHANGELOG.md
  app/controllers/ReportsController.php
  config.php
  instance.php
  themes/default/views/classes/classContents.php
Labels: Pronto para merge

#990 Fix/observation student
  CHANGELOG.md
  app/controllers/ClassesController.php
Labels: Pronto para merge

#984 Fix/sagres food component name
  CHANGELOG.md
  app/modules/sagres/models/SagresConsultModel.php
  config.php
Labels: High priority, Pronto para merge
