Repository ipti/br.tag, pull requests merged in 2025-03, with the labels that each got.

#936 [TCDA-897] Fix/Instructor_frequency_current_year
  CHANGELOG.md
  app/controllers/InstructorController.php
  config.php
Labels: Pronto para merge

#937 [TCDA-839] Fix/Delete classroom
  CHANGELOG.md
  app/controllers/ClassroomController.php
  app/migrations/2025-12-03_experience_fields/sql.sql
  config.php
Labels: Pronto para merge

#948 fix/class_contents_year
  CHANGELOG.md
  app/controllers/ClassesController.php
  config.php
Labels: Pronto para merge

#956 [TCDA-921, TCDA-928 & TCDA-932] Fix/student frequency
  CHANGELOG.md
  app/controllers/EnrollmentController.php
  app/controllers/StudentController.php
  app/messages/pt_br/default.php
  app/migrations/2025-19-03_merge_column_student_enrollment/sql.sql
  themes/default/views/enrollment/_form.php
  themes/default/views/student/_form.php
Labels: Pronto para merge

#949 [TCDA-890] Fix/classroom_stage_update
  CHANGELOG.md
  app/migrations/2025-14-03_classroom_esvm_fieldsize/sql.sql
  config.php
Labels: Pronto para merge

#941 Fix/Adjust on timesheet view
  themes/default/views/timesheet/timesheet/index.php
Labels: hotfix, Pronto para merge

#932 [TCDA-839] Fix/Delete instructor restriction
  CHANGELOG.md
  app/controllers/InstructorController.php
  app/models/InstructorIdentification.php
  themes/default/views/instructor/index.php
Labels: Pronto para merge

#946 chore/pr-templates
  .github/code_review_template.md
  .github/pull_request_template.md
Labels: Aguardando review 1, Pronto para merge

#962 Fix/delete classroom with grade rules
  app/controllers/ClassroomController.php
  instance.php
  js/classroom/form/_initialization.js
Labels: Pronto para merge

#957 fix/ change https for http
  app/modules/sagres/soap/src/sagresEdu/EducacaoTType.php
Labels: Aguardando review 1, Aguardando review 2
